In [1]:
import os
from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# load the songs data

df_songs = pd.read_csv(r'D:\vs code projects\spotify_recommender_system\data\raw\Music Info.csv')
df_songs.head()

,track_id,name,artist,spotify_preview_url,spotify_id,tags,genre,year,duration_ms,danceability,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,TRIOREW128F424EAF0,Mr. Brightside,The Killers,https://p.scdn.co/mp3-preview/4d26180e6961fd46...,09ZQ5TmUG8TSL56n0knqrj,"rock, alternative, indie, alternative_rock, in...",NaN,2004,222200,0.355,...,1,-4.360,1,0.0746,0.001190,0.000000,0.0971,0.240,148.114,4
1,TRRIVDJ128F429B0E8,Wonderwall,Oasis,https://p.scdn.co/mp3-preview/d012e536916c927b...,06UfBBDISthj1ZJAtX4xjj,"rock, alternative, indie, pop, alternative_roc...",NaN,2006,258613,0.409,...,2,-4.373,1,0.0336,0.000807,0.000000,0.2070,0.651,174.426,4
2,TROUVHL128F426C441,Come as You Are,Nirvana,https://p.scdn.co/mp3-preview/a1c11bb1cb231031...,0keNu0t0tqsWtExGM3nT1D,"rock, alternative, alternative_rock, 90s, grunge",RnB,1991,218920,0.508,...,4,-5.783,0,0.0400,0.000175,0.000459,0.0878,0.543,120.012,4
3,TRUEIND128F93038C4,Take Me Out,Franz Ferdinand,https://p.scdn.co/mp3-preview/399c401370438be4...,0ancVQ9wEcHVd0RrGICTE4,"rock, alternative, indie, alternative_rock, in...",NaN,2004,237026,0.279,...,9,-8.851,1,0.0371,0.000389,0.000655,0.1330,0.490,104.560,4
4,TRLNZBD128F935E4D8,Creep,Radiohead,https://p.scdn.co/mp3-preview/e7eb60e9466bc3a2...,01QoK9DA7VTeTSE3MNzp4I,"rock, alternative, indie, alternative_rock, in...",RnB,2008,238640,0.515,...,7,-9.935,1,0.0369,0.010200,0.000141,0.1290,0.104,91.841,4

# Getting the dataset ready

In [3]:
# shape of the data

df_songs.shape

(50683, 21)

In [4]:
# data info

df_songs.info()

<class 'pandas.DataFrame'>
RangeIndex: 50683 entries, 0 to 50682
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   track_id             50683 non-null  str
 1   name                 50683 non-null  str
 2   artist               50683 non-null  str
 3   spotify_preview_url  50683 non-null  str
 4   spotify_id           50683 non-null  str
 5   tags                 49556 non-null  str
 6   genre                22348 non-null  str
 7   year                 50683 non-null  int64
 8   duration_ms          50683 non-null  int64
 9   danceability         50683 non-null  float64
 10  energy               50683 non-null  float64
 11  key                  50683 non-null  int64
 12  loudness             50683 non-null  float64
 13  mode                 50683 non-null  int64
 14  speechiness          50683 non-null  float64
 15  acousticness         50683 non-null  float64
 16  instrumentalness     50683 non-null  float64
 17  liveness             50683 non-null  float64
 18  valence              50683 non-null  float64
 19  tempo                50683 non-null  float64
 20  time_signature       50683 non-null  int64
dtypes: float64(9), int64(5), str(7)
memory usage: 18.3 MB

In [5]:
# missing values

df_songs.isna().sum()

track_id                   0
name                       0
artist                     0
spotify_preview_url        0
spotify_id                 0
tags                    1127
genre                  28335
year                       0
duration_ms                0
danceability               0
energy                     0
key                        0
loudness                   0
mode                       0
speechiness                0
acousticness               0
instrumentalness           0
liveness                   0
valence                    0
tempo                      0
time_signature             0
dtype: int64

In [6]:
# ratio of missing values in data

(
    df_songs
    .isna()
    .mean()
    .sort_values(ascending=False)
    .head(2)
    .mul(100)
)

genre    55.906320
tags      2.223625
dtype: float64

In [7]:
# duplicates in the data based on spotify_id

(
    df_songs
    .duplicated(subset="spotify_id")
    .sum()
)

np.int64(9)

In [8]:
# drop duplicates

df_songs.drop_duplicates(subset=["spotify_id","year","duration_ms"],inplace=True)

In [9]:
# check for duplicates

(
    df_songs
    .duplicated(subset=["spotify_id","year","duration_ms"])
    .sum()
)

np.int64(0)

In [10]:
df_songs.head()

,track_id,name,artist,spotify_preview_url,spotify_id,tags,genre,year,duration_ms,danceability,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,TRIOREW128F424EAF0,Mr. Brightside,The Killers,https://p.scdn.co/mp3-preview/4d26180e6961fd46...,09ZQ5TmUG8TSL56n0knqrj,"rock, alternative, indie, alternative_rock, in...",NaN,2004,222200,0.355,...,1,-4.360,1,0.0746,0.001190,0.000000,0.0971,0.240,148.114,4
1,TRRIVDJ128F429B0E8,Wonderwall,Oasis,https://p.scdn.co/mp3-preview/d012e536916c927b...,06UfBBDISthj1ZJAtX4xjj,"rock, alternative, indie, pop, alternative_roc...",NaN,2006,258613,0.409,...,2,-4.373,1,0.0336,0.000807,0.000000,0.2070,0.651,174.426,4
2,TROUVHL128F426C441,Come as You Are,Nirvana,https://p.scdn.co/mp3-preview/a1c11bb1cb231031...,0keNu0t0tqsWtExGM3nT1D,"rock, alternative, alternative_rock, 90s, grunge",RnB,1991,218920,0.508,...,4,-5.783,0,0.0400,0.000175,0.000459,0.0878,0.543,120.012,4
3,TRUEIND128F93038C4,Take Me Out,Franz Ferdinand,https://p.scdn.co/mp3-preview/399c401370438be4...,0ancVQ9wEcHVd0RrGICTE4,"rock, alternative, indie, alternative_rock, in...",NaN,2004,237026,0.279,...,9,-8.851,1,0.0371,0.000389,0.000655,0.1330,0.490,104.560,4
4,TRLNZBD128F935E4D8,Creep,Radiohead,https://p.scdn.co/mp3-preview/e7eb60e9466bc3a2...,01QoK9DA7VTeTSE3MNzp4I,"rock, alternative, indie, alternative_rock, in...",RnB,2008,238640,0.515,...,7,-9.935,1,0.0369,0.010200,0.000141,0.1290,0.104,91.841,4

In [11]:
# reset the index

df_songs.reset_index(drop=True,inplace=True)

In [13]:
# remove columns not required for collaborative filtering

cols_to_remove = ["track_id","name","spotify_preview_url","spotify_id","genre"]


df_colab_filtering = df_songs.drop(columns=cols_to_remove)

df_colab_filtering

,artist,tags,year,duration_ms,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,The Killers,"rock, alternative, indie, alternative_rock, in...",2004,222200,0.355,0.918,1,-4.360,1,0.0746,0.001190,0.000000,0.0971,0.240,148.114,4
1,Oasis,"rock, alternative, indie, pop, alternative_roc...",2006,258613,0.409,0.892,2,-4.373,1,0.0336,0.000807,0.000000,0.2070,0.651,174.426,4
2,Nirvana,"rock, alternative, alternative_rock, 90s, grunge",1991,218920,0.508,0.826,4,-5.783,0,0.0400,0.000175,0.000459,0.0878,0.543,120.012,4
3,Franz Ferdinand,"rock, alternative, indie, alternative_rock, in...",2004,237026,0.279,0.664,9,-8.851,1,0.0371,0.000389,0.000655,0.1330,0.490,104.560,4
4,Radiohead,"rock, alternative, indie, alternative_rock, in...",2008,238640,0.515,0.430,7,-9.935,1,0.0369,0.010200,0.000141,0.1290,0.104,91.841,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50669,アンティック-珈琲店-,NaN,2008,273440,0.438,0.933,6,-3.062,0,0.1650,0.003120,0.000000,0.1300,0.421,166.956,4
50670,ACIDMAN,"rock, alternative_rock, japanese, cover",2004,275133,0.351,0.693,0,-6.811,1,0.1200,0.000940,0.000049,0.1920,0.450,200.350,4
50671,coldrain,"metal, metalcore, post_hardcore",2014,254826,0.434,0.975,10,-3.092,0,0.2680,0.000108,0.001410,0.1630,0.282,158.025,4
50672,アンティック-珈琲店-,NaN,2008,243293,0.513,0.902,4,-3.914,0,0.0530,0.000715,0.001350,0.0571,0.618,109.923,4
50673,9mm Parabellum Bullet,"rock, japanese",2008,131960,0.190,0.953,8,-4.144,1,0.1310,0.000033,0.051100,0.2030,0.138,136.475,4

In [14]:
# check for missing values

df_colab_filtering.isna().sum()

artist                 0
tags                1126
year                   0
duration_ms            0
danceability           0
energy                 0
key                    0
loudness               0
mode                   0
speechiness            0
acousticness           0
instrumentalness       0
liveness               0
valence                0
tempo                  0
time_signature         0
dtype: int64

In [15]:
# fill the tags column missing values with string "no_tags"

df_colab_filtering.fillna({"tags":"no_tags"},inplace=True)

,artist,tags,year,duration_ms,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,The Killers,"rock, alternative, indie, alternative_rock, in...",2004,222200,0.355,0.918,1,-4.360,1,0.0746,0.001190,0.000000,0.0971,0.240,148.114,4
1,Oasis,"rock, alternative, indie, pop, alternative_roc...",2006,258613,0.409,0.892,2,-4.373,1,0.0336,0.000807,0.000000,0.2070,0.651,174.426,4
2,Nirvana,"rock, alternative, alternative_rock, 90s, grunge",1991,218920,0.508,0.826,4,-5.783,0,0.0400,0.000175,0.000459,0.0878,0.543,120.012,4
3,Franz Ferdinand,"rock, alternative, indie, alternative_rock, in...",2004,237026,0.279,0.664,9,-8.851,1,0.0371,0.000389,0.000655,0.1330,0.490,104.560,4
4,Radiohead,"rock, alternative, indie, alternative_rock, in...",2008,238640,0.515,0.430,7,-9.935,1,0.0369,0.010200,0.000141,0.1290,0.104,91.841,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50669,アンティック-珈琲店-,no_tags,2008,273440,0.438,0.933,6,-3.062,0,0.1650,0.003120,0.000000,0.1300,0.421,166.956,4
50670,ACIDMAN,"rock, alternative_rock, japanese, cover",2004,275133,0.351,0.693,0,-6.811,1,0.1200,0.000940,0.000049,0.1920,0.450,200.350,4
50671,coldrain,"metal, metalcore, post_hardcore",2014,254826,0.434,0.975,10,-3.092,0,0.2680,0.000108,0.001410,0.1630,0.282,158.025,4
50672,アンティック-珈琲店-,no_tags,2008,243293,0.513,0.902,4,-3.914,0,0.0530,0.000715,0.001350,0.0571,0.618,109.923,4
50673,9mm Parabellum Bullet,"rock, japanese",2008,131960,0.190,0.953,8,-4.144,1,0.1310,0.000033,0.051100,0.2030,0.138,136.475,4

In [16]:
# check for missing values

df_colab_filtering.isna().sum().sum()

np.int64(0)

In [17]:
# artist names as lower case

df_colab_filtering["artist"] = df_colab_filtering["artist"].str.lower()

In [18]:
# number of unique artists

(
    df_songs
    .loc[:,'artist']
    .nunique()
)

8317

In [19]:
# number of unique year values

(
    df_songs
    .loc[:,'year']
    .nunique()
)

75

In [20]:
# min and max values of numerical columns

(
    df_songs
    .select_dtypes(include='number')
    .agg(['min','max'])
)

,year,duration_ms,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
min,1900,1439,0.000,0.0,0,-60.000,0,0.000,0.000,0.000,0.000,0.000,0.000,0
max,2022,3816373,0.986,1.0,11,3.642,1,0.954,0.996,0.999,0.999,0.993,238.895,5

In [21]:
# value counts for the tags

(
    df_songs
    .loc[:,'tags']
    .str.lower()
    .str.split(',')
    .explode()
    .str.strip()
    .value_counts()
)

tags
rock            10681
indie            7284
electronic       6592
alternative      6271
pop              4650
                ...
dark_ambient      602
japanese          489
polish            411
j_pop             213
russian           127
Name: count, Length: 100, dtype: int64

In [22]:
# value counts for the tags

(
    df_songs
    .loc[:,'tags']
    .str.lower()
    .str.split(',')
    .explode()
    .str.strip()
    .value_counts()
    .loc[lambda ser: ser >= 1000]
)

tags
rock            10681
indie            7284
electronic       6592
alternative      6271
pop              4650
                ...
ska              1088
gothic_metal     1072
grindcore        1040
french           1018
nu_metal         1006
Name: count, Length: 85, dtype: int64

In [23]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler, OneHotEncoder
from category_encoders.count import CountEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.compose import ColumnTransformer

In [24]:
df_colab_filtering.head(3)

,artist,tags,year,duration_ms,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,the killers,"rock, alternative, indie, alternative_rock, in...",2004,222200,0.355,0.918,1,-4.360,1,0.0746,0.001190,0.000000,0.0971,0.240,148.114,4
1,oasis,"rock, alternative, indie, pop, alternative_roc...",2006,258613,0.409,0.892,2,-4.373,1,0.0336,0.000807,0.000000,0.2070,0.651,174.426,4
2,nirvana,"rock, alternative, alternative_rock, 90s, grunge",1991,218920,0.508,0.826,4,-5.783,0,0.0400,0.000175,0.000459,0.0878,0.543,120.012,4

In [25]:
df_colab_filtering.shape

(50674, 16)

In [26]:
# cols to transform

frequency_encode_cols = ['year']
ohe_cols = ['artist',"time_signature","key"]
tfidf_col = 'tags'
standard_scale_cols = ["duration_ms","loudness","tempo"]
min_max_scale_cols = ["danceability","energy","speechiness","acousticness","instrumentalness","liveness","valence"]

In [27]:
len(frequency_encode_cols + ohe_cols + standard_scale_cols + min_max_scale_cols)

14

In [29]:
# transform the data

transformer = ColumnTransformer(transformers=[
    ("frequency_encode", CountEncoder(normalize=True,return_df=True), frequency_encode_cols),
    ("ohe", OneHotEncoder(handle_unknown="ignore"), ohe_cols),
    ("tfidf", TfidfVectorizer(max_features=85), tfidf_col),
    ("standard_scale", StandardScaler(), standard_scale_cols),
    ("min_max_scale", MinMaxScaler(), min_max_scale_cols)
],remainder='passthrough',n_jobs=-1)

transformer

ColumnTransformer(n_jobs=-1, remainder='passthrough',
                  transformers=[('frequency_encode',
                                 CountEncoder(combine_min_nan_groups=True,
                                              normalize=True),
                                 ['year']),
                                ('ohe', OneHotEncoder(handle_unknown='ignore'),
                                 ['artist', 'time_signature', 'key']),
                                ('tfidf', TfidfVectorizer(max_features=85),
                                 'tags'),
                                ('standard_scale', StandardScaler(),
                                 ['duration_ms', 'loudness', 'tempo']),
                                ('min_max_scale', MinMaxScaler(),
                                 ['danceability', 'energy', 'speechiness',
                                  'acousticness', 'instrumentalness',
                                  'liveness', 'valence'])])

In [30]:
# fit the transformer

transformer.fit(df_colab_filtering)

ColumnTransformer(n_jobs=-1, remainder='passthrough',
                  transformers=[('frequency_encode',
                                 CountEncoder(combine_min_nan_groups=True,
                                              normalize=True),
                                 ['year']),
                                ('ohe', OneHotEncoder(handle_unknown='ignore'),
                                 ['artist', 'time_signature', 'key']),
                                ('tfidf', TfidfVectorizer(max_features=85),
                                 'tags'),
                                ('standard_scale', StandardScaler(),
                                 ['duration_ms', 'loudness', 'tempo']),
                                ('min_max_scale', MinMaxScaler(),
                                 ['danceability', 'energy', 'speechiness',
                                  'acousticness', 'instrumentalness',
                                  'liveness', 'valence'])])

In [31]:
# transform the data

transformed_df = transformer.transform(df_colab_filtering)

In [32]:
transformed_df.shape

(50674, 8431)

In [33]:
transformed_df

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 907911 stored elements and shape (50674, 8431)>

In [34]:
from sklearn.metrics.pairwise import cosine_similarity

In [35]:
# fetch a song where artist is Shakira

df_songs.loc[df_songs["artist"] == "Shakira"]

,track_id,name,artist,spotify_preview_url,spotify_id,tags,genre,year,duration_ms,danceability,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
1025,TRLWDVU128F932B093,"Whenever, Wherever",Shakira,https://p.scdn.co/mp3-preview/09ddeb4ae33ee6e8...,07PHBDuUmOeZ7jeKSbAbKi,"rock, pop, female_vocalists, singer_songwriter...",NaN,2012,196826,0.787,...,1,-4.967,0,0.0474,0.29800,0.000005,0.2060,0.860,107.674,4
2068,TRILOWN128F426080F,Underneath Your Clothes,Shakira,https://p.scdn.co/mp3-preview/6c5a56058ce04371...,07qRl4PT2lA6O3KN40McLz,"rock, pop, female_vocalists, singer_songwriter...",Pop,2013,224893,0.707,...,8,-5.293,1,0.0298,0.69100,0.000000,0.1030,0.407,82.784,4
2205,TRXLMFJ12903CC06F7,She Wolf,Shakira,https://p.scdn.co/mp3-preview/4dc802fd3b06fcb5...,075xFXR0JDBwFPVinG1ig5,"electronic, pop, female_vocalists, experimenta...",NaN,2009,187866,0.857,...,7,-6.480,1,0.0428,0.32300,0.003220,0.3140,0.868,121.994,4
2469,TRSQAWU128F92EA20F,La Tortura,Shakira,https://p.scdn.co/mp3-preview/e62ae4649f029729...,0ofDrTTcinCUxm7wqCLPQa,"electronic, pop, female_vocalists, singer_song...",Latin,2011,213106,0.741,...,0,-5.904,1,0.0421,0.02300,0.000788,0.1200,0.834,100.001,4
3373,TRINUNP12903CD84D9,Did It Again,Shakira,https://p.scdn.co/mp3-preview/5477eae2283113ff...,0eMNEdcC5OImvrfn79J9dU,"electronic, pop, female_vocalists, experimenta...",NaN,2009,227333,0.869,...,5,-5.069,0,0.0896,0.50900,0.000000,0.0741,0.599,137.955,4
4318,TROLUWR128F92E5858,Te Dejo Madrid,Shakira,https://p.scdn.co/mp3-preview/bcaccba847a5cf53...,0IESLhxv5iqXvMH5mm3z88,"pop, experimental, singer_songwriter, dance, l...",NaN,2001,187333,0.741,...,11,-5.011,1,0.0379,0.02440,0.000015,0.2830,0.926,131.017,4
4599,TRLNLES128F932DA8E,Fool,Shakira,https://p.scdn.co/mp3-preview/4ce283ae87d032f5...,0MttJjfO3pkTHJgVdXqPcP,"rock, pop, female_vocalists, acoustic, pop_rock",Rap,2001,230333,0.640,...,3,-5.848,1,0.0241,0.04560,0.000000,0.0988,0.420,100.994,4
4617,TRUIPZL12903CA0BFE,Rules,Shakira,https://p.scdn.co/mp3-preview/e5c557dc2b36006a...,1f7TZQzs4UikFQIzeWOtOj,"pop, female_vocalists, singer_songwriter, pop_...",NaN,2001,219106,0.692,...,5,-6.365,0,0.0418,0.03590,0.000002,0.1850,0.775,149.000,4
6046,TRAAKDG128F42A0ECB,Hips Don't Lie,Shakira,https://p.scdn.co/mp3-preview/3859547944f57cfb...,01Yj2MCGpjZs34PRlGgz4K,"pop, female_vocalists, singer_songwriter, danc...",Pop,2001,217453,0.777,...,10,-5.867,0,0.0734,0.28400,0.000000,0.4300,0.760,100.003,4
6818,TRBAHID128F4278EAF,Objection (Tango),Shakira,https://p.scdn.co/mp3-preview/bf65095d5ce58358...,0p9QhtUdbyDAQ6k14hQ2i3,"pop, female_vocalists, singer_songwriter, danc...",Pop,2001,222533,0.603,...,11,-5.282,0,0.0677,0.01470,0.000000,0.0246,0.705,179.344,4
7007,TRHEBDB128F92E9FC0,Don't Bother,Shakira,https://p.scdn.co/mp3-preview/d778abba87ff5de6...,08cuRs7v0vmBrYttD3BEPq,"rock, pop, female_vocalists, singer_songwriter...",Pop,2009,256800,0.620,...,7,-6.297,1,0.0420,0.00552,0.000990,0.1510,0.209,129.970,4
11904,TRADBSW128F933A7A8,Loba,Shakira,https://p.scdn.co/mp3-preview/8fd280cc8c535862...,1fPCGREltHJuV3axEPydLp,"electronic, pop, experimental, singer_songwrit...",NaN,2009,189200,0.853,...,7,-7.598,1,0.0451,0.40300,0.046000,0.0751,0.778,121.991,4
12305,TRYFVKK128F4240FE8,Why Wait,Shakira,https://p.scdn.co/mp3-preview/d78c90c5cb5626be...,0HiJFRxWme9myvUiDlqQ8q,"pop, experimental, singer_songwriter, dance",NaN,2001,221240,0.887,...,1,-5.535,0,0.0431,0.14400,0.000590,0.1230,0.399,129.943,4
12322,TROZGSI128F92EA0AE,La Pared,Shakira,https://p.scdn.co/mp3-preview/91217265ccb8fc80...,07xN9EAHMx7UVppVqSoPDF,"pop, experimental, singer_songwriter, piano",NaN,2005,199173,0.755,...,8,-7.101,1,0.0329,0.63800,0.003540,0.1020,0.615,129.015,4
16859,TRAFCNH12903CA072C,Inevitable,Shakira,https://p.scdn.co/mp3-preview/88da75b50a528fe6...,0d13t5pyd1kL6geJ5JnSjs,"rock, pop, singer_songwriter, 90s, acoustic, b...",NaN,2001,193440,0.641,...,6,-7.486,1,0.0621,0.23100,0.000083,0.1280,0.340,92.119,4
16945,TRUGCOP128F4232463,Si te vas,Shakira,https://p.scdn.co/mp3-preview/54633474ff7aafb1...,13wWKN82EOZze70szgY48s,"rock, pop, singer_songwriter, 90s, beautiful",NaN,1998,210600,0.676,...,2,-5.231,1,0.0407,0.04340,0.000000,0.3080,0.823,107.809,4
27040,TRSAGEK128F9333C7C,Lo Imprescindible,Shakira,https://p.scdn.co/mp3-preview/0b112235150f3381...,0ta0VCgTnBANe0fhXAYs0l,"pop, female_vocalists, german",NaN,2005,234866,0.697,...,9,-5.975,0,0.0309,0.23000,0.000001,0.3310,0.442,112.980,3
29943,TRUIESB128F427D70D,Tú,Shakira,https://p.scdn.co/mp3-preview/156365b8cbc625ee...,0XKKsfwzAhsLEKEDwARXX6,"pop, piano",NaN,2001,214546,0.569,...,0,-8.449,1,0.0254,0.68600,0.000002,0.2590,0.219,139.781,4
32180,TROSDVD12903CB116F,Mon Amour,Shakira,https://p.scdn.co/mp3-preview/3d0045ee2fddfb77...,0cwSydbpCned8mhZqTUHyb,"rock, pop, female_vocalists, singer_songwriter...",NaN,2001,245066,0.618,...,9,-2.848,0,0.1100,0.04320,0.000005,0.0989,0.421,144.008,4
38383,TRWUWRZ128F42ADA4A,Dreams for Plans,Shakira,https://p.scdn.co/mp3-preview/6e2c021846087a88...,2ObxMmMaDINr0ynkqW2BlY,"pop, female_vocalists, guitar, pop_rock",Pop,2005,242760,0.689,...,1,-7.427,1,0.0286,0.18000,0.000038,0.0844,0.548,96.098,4
38415,TRNHCIP128F42ADA54,Costume Makes the Clown,Shakira,https://p.scdn.co/mp3-preview/762595070b8b966d...,0R6MQ8AoHDcsg21xX0EWkZ,"rock, pop, female_vocalists, singer_songwriter...",NaN,2005,192133,0.537,...,8,-4.728,1,0.0374,0.05000,0.000000,0.1210,0.503,162.010,4
42428,TRGJXTC128F4278ECC,Que Me Quedes Tu,Shakira,https://p.scdn.co/mp3-preview/18c4b856a3a5c741...,1Gpb4mSdcDoFcOPajj8WKd,"pop, female_vocalists, pop_rock",Latin,2001,287333,0.765,...,7,-8.314,0,0.0271,0.27400,0.000071,0.2760,0.417,113.023,4
42446,TRCYQFE128F42ADA40,Animal City,Shakira,https://p.scdn.co/mp3-preview/23892da2ddc26b6c...,1gI8mnirWfPjh9jamSCNMW,"rock, pop, female_vocalists, singer_songwriter...",Pop,2005,195493,0.783,...,6,-4.407,0,0.1080,0.17100,0.000000,0.4350,0.893,140.039,4
42507,TRYTKQE128F42ADA50,Your Embrace,Shakira,https://p.scdn.co/mp3-preview/63b29a594f6d6976...,11pHuqmviC29FYrvFlj7ro,"pop, female_vocalists, love, mellow, pop_rock",Pop,2005,213000,0.427,...,0,-8.346,1,0.0470,0.33900,0.000000,0.3430,0.245,167.873,4
42555,TRFNIOO128F42AD944,Donde Estas Corazon,Shakira,https://p.scdn.co/mp3-preview/28b6b0789340e733...,16P23ucGLZUBMOa8rh9hZW,"female_vocalists, pop_rock",NaN,1996,231693,0.743,...,7,-9.212,1,0.0722,0.06350,0.000000,0.1260,0.597,109.044,4
43697,TRANQLL128F92F5263,Poem to a Horse,Shakira,https://p.scdn.co/mp3-preview/d6e5a567e639f673...,0QjOc0jrhT8DLSnkjwLlIy,"rock, pop, female_vocalists, pop_rock",Pop,2001,246426,0.644,...,11,-5.751,0,0.0377,0.02700,0.000004,0.1490,0.695,94.014,4
43705,TRIXHNL128F1496B61,Sale el Sol,Shakira,https://p.scdn.co/mp3-preview/83185ae92ade51e7...,0vuIlEP410klUy30tkNziu,"pop, female_vocalists, pop_rock",NaN,2010,200133,0.698,...,0,-5.925,1,0.0293,0.15500,0.000000,0.1030,0.257,119.006,4
43707,TRULZUZ128F427D869,Ready for the Good Times,Shakira,https://p.scdn.co/mp3-preview/cc7e2fa060501a1c...,0JiTG5OhLKlOXBuCGCbAKL,"pop, singer_songwriter, dance, pop_rock, drum_...",NaN,2001,253066,0.767,...,0,-6.249,0,0.0397,0.18400,0.001840,0.1140,0.829,121.003,4
43728,TRULHLZ128F42BB903,Illegal,Shakira,https://p.scdn.co/mp3-preview/fffbeba5d53973dc...,0N0DOF0MXnlFv3CdAk9cDb,"pop, female_vocalists, pop_rock",NaN,2005,233840,0.669,...,2,-8.662,1,0.0416,0.64500,0.000036,0.1120,0.609,147.949,4
43884,TRDENYV128F4295BF9,"Pies Descalzos, Sueños Blancos",Shakira,https://p.scdn.co/mp3-preview/079500681067456b...,0BBL6G7tp5z5h6JD23o53D,"rock, pop_rock",NaN,1996,205800,0.854,...,6,-7.333,0,0.0361,0.00854,0.000000,0.1520,0.673,119.957,4

In [36]:
# build input vector

df_songs[df_songs["name"] == "Whenever, Wherever"]

song_input = df_colab_filtering[df_songs["name"] == "Whenever, Wherever"]

song_input

,artist,tags,year,duration_ms,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
1025,shakira,"rock, pop, female_vocalists, singer_songwriter...",2012,196826,0.787,0.828,1,-4.967,0,0.0474,0.298,0.000005,0.206,0.86,107.674,4

In [37]:
# input vector to calculate similarity

input_vector = transformer.transform(song_input)

input_vector

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 20 stored elements and shape (1, 8431)>

In [38]:
# calculate the similarity matrix

similarity_scores = cosine_similarity(transformed_df,input_vector)

In [39]:
similarity_scores.shape

(50674, 1)

In [40]:
similarity_scores

array([[0.99999914],
       [0.99999847],
       [0.99999921],
       ...,
       [0.99999877],
       [0.9999992 ],
       [0.99999891]], shape=(50674, 1))

In [41]:
top_10_songs_indexes = np.argsort(similarity_scores.ravel())[-11:][::-1]

In [42]:
top_10_songs_indexes

array([ 1025, 12305,  6046,  6129, 17241,  6133,  7172,  6121,  6526,
       38383,  6287])

In [43]:
top_10_songs_names = df_songs.iloc[top_10_songs_indexes]

In [44]:
top_10_songs_names

,track_id,name,artist,spotify_preview_url,spotify_id,tags,genre,year,duration_ms,danceability,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
1025,TRLWDVU128F932B093,"Whenever, Wherever",Shakira,https://p.scdn.co/mp3-preview/09ddeb4ae33ee6e8...,07PHBDuUmOeZ7jeKSbAbKi,"rock, pop, female_vocalists, singer_songwriter...",NaN,2012,196826,0.787,...,1,-4.967,0,0.0474,0.29800,0.000005,0.2060,0.860,107.674,4
12305,TRYFVKK128F4240FE8,Why Wait,Shakira,https://p.scdn.co/mp3-preview/d78c90c5cb5626be...,0HiJFRxWme9myvUiDlqQ8q,"pop, experimental, singer_songwriter, dance",NaN,2001,221240,0.887,...,1,-5.535,0,0.0431,0.14400,0.000590,0.1230,0.399,129.943,4
6046,TRAAKDG128F42A0ECB,Hips Don't Lie,Shakira,https://p.scdn.co/mp3-preview/3859547944f57cfb...,01Yj2MCGpjZs34PRlGgz4K,"pop, female_vocalists, singer_songwriter, danc...",Pop,2001,217453,0.777,...,10,-5.867,0,0.0734,0.28400,0.000000,0.4300,0.760,100.003,4
6129,TRBAUVN128F932FEF8,Oops!...I Did It Again,Britney Spears,https://p.scdn.co/mp3-preview/7fb86827422540ad...,095uakqDYR50Uza0mxvPWB,"pop, female_vocalists, dance, 00s",Pop,2014,211786,0.751,...,1,-5.351,0,0.0435,0.34000,0.000018,0.2550,0.886,95.045,4
17241,TRMBDIR128F4279C1F,Perfect Lover,Britney Spears,https://p.scdn.co/mp3-preview/52671e54d36f077e...,1BhxPx4evrx8X02RHGrLdi,"pop, dance, rnb, 00s",Rock,2007,182680,0.718,...,1,-3.959,0,0.0360,0.35300,0.000390,0.1020,0.805,117.067,4
6133,TRDXCSH128F92ED4A1,Bootylicious,Destiny's Child,https://p.scdn.co/mp3-preview/7e327ccb1e4c52b2...,09mkdGhqb5ySKVsnkx9hy2,"pop, female_vocalists, dance, soul, hip_hop, r...",NaN,2001,207733,0.835,...,1,-4.364,0,0.2840,0.00247,0.000000,0.1710,0.586,103.358,4
7172,TRLQBEN128F92E7415,Wild Things,Alessia Cara,https://p.scdn.co/mp3-preview/c13f00088525d0b2...,0RgHkNpqtAHGGBVro6mmqD,"pop, female_vocalists",Country,2016,188493,0.741,...,1,-5.362,0,0.1080,0.01950,0.000000,0.0822,0.735,107.960,4
6121,TRGZIMZ128F930A016,La Isla Bonita,Madonna,https://p.scdn.co/mp3-preview/d8f3cafe99c1f0cd...,0rpndqrkU9y9nckNCfjcq6,"pop, female_vocalists, dance, 80s",NaN,2009,242946,0.708,...,1,-4.736,0,0.0362,0.39200,0.000001,0.0561,0.968,99.953,4
6526,TRXHWIA128E078A9BB,Cruel Summer,Bananarama,https://p.scdn.co/mp3-preview/47d13ef240a58bef...,0BmUCeyXpTrUVahHKVFxuB,"pop, female_vocalists, dance, 80s, new_wave",NaN,1984,209573,0.665,...,1,-5.828,0,0.0278,0.25000,0.008550,0.0537,0.932,108.429,4
38383,TRWUWRZ128F42ADA4A,Dreams for Plans,Shakira,https://p.scdn.co/mp3-preview/6e2c021846087a88...,2ObxMmMaDINr0ynkqW2BlY,"pop, female_vocalists, guitar, pop_rock",Pop,2005,242760,0.689,...,1,-7.427,1,0.0286,0.18000,0.000038,0.0844,0.548,96.098,4
6287,TRZJJHG128EF34A3F9,Trick Me,Kelis,https://p.scdn.co/mp3-preview/0862413f9e28d284...,03obQpbRm2JsmEg8jnmMgL,"pop, female_vocalists, dance, soul, hip_hop, rnb",NaN,2012,206320,0.970,...,1,-4.443,0,0.1570,0.03780,0.000262,0.3160,0.961,107.175,4

In [45]:
def recommend(song_name, songs_data, transformed_data, k=10):
    """
    Recommends top k songs similar to the given song based on content-based filtering.

    Parameters:
    song_name (str): The name of the song to base the recommendations on.
    songs_data (DataFrame): The DataFrame containing song information.
    transformed_data (ndarray): The transformed data matrix for similarity calculations.
    k (int, optional): The number of similar songs to recommend. Default is 10.

    Returns:
    DataFrame: A DataFrame containing the top k recommended songs with their names, artists, and Spotify preview URLs.
    """
    # filter out the song from data
    song_row = songs_data.loc[songs_data["name"] == song_name,:]
    if song_row.empty:
        print("Song not found in the dataset.")
    else:
        # get the index of song
        song_index = song_row.index[0]
        print(song_index)
        # generate the input vector
        input_vector = transformed_data[song_index].reshape(1,-1)
        # calculate similarity scores
        similarity_scores = cosine_similarity(input_vector, transformed_data)
        print(similarity_scores.shape)
        # get the top k songs
        top_k_songs_indexes = np.argsort(similarity_scores.ravel())[-k-1:][::-1]
        print(top_k_songs_indexes)
        # get the top k songs names
        top_k_songs_names = songs_data.iloc[top_k_songs_indexes]
        # print the top k songs
        top_k_list = top_k_songs_names[['name','artist','spotify_preview_url']].reset_index(drop=True)
        return top_k_list

In [46]:
# recommend song using the function

recommend("Whenever, Wherever",songs_data=df_songs,transformed_data=transformed_df,k=10)

1025
(1, 50674)
[ 1025 12305  6046  6129 17241  6133  7172  6121  6526 38383  6287]

,name,artist,spotify_preview_url
0,"Whenever, Wherever",Shakira,https://p.scdn.co/mp3-preview/09ddeb4ae33ee6e8...
1,Why Wait,Shakira,https://p.scdn.co/mp3-preview/d78c90c5cb5626be...
2,Hips Don't Lie,Shakira,https://p.scdn.co/mp3-preview/3859547944f57cfb...
3,Oops!...I Did It Again,Britney Spears,https://p.scdn.co/mp3-preview/7fb86827422540ad...
4,Perfect Lover,Britney Spears,https://p.scdn.co/mp3-preview/52671e54d36f077e...
5,Bootylicious,Destiny's Child,https://p.scdn.co/mp3-preview/7e327ccb1e4c52b2...
6,Wild Things,Alessia Cara,https://p.scdn.co/mp3-preview/c13f00088525d0b2...
7,La Isla Bonita,Madonna,https://p.scdn.co/mp3-preview/d8f3cafe99c1f0cd...
8,Cruel Summer,Bananarama,https://p.scdn.co/mp3-preview/47d13ef240a58bef...
9,Dreams for Plans,Shakira,https://p.scdn.co/mp3-preview/6e2c021846087a88...
10,Trick Me,Kelis,https://p.scdn.co/mp3-preview/0862413f9e28d284...